export enum EPaveStyle {
  CONTINUOUS_PAVING = 'CONTINUOUS_PAVING',
  I_SHAPED_PAVING = 'I_SHAPED_PAVING',
  THREE_SIX_NINE_PAVING = 'THREE_SIX_NINE_PAVING',
  SINGLE_BRICK_HERRINGB_ONE_PAVING = 'SINGLE_BRICK_HERRINGB_ONE_PAVING',
  FISHBONE_PAVING = 'FISHBONE_PAVING',
}

export enum EPavePosition {
  LOWER_LEFT = 'LOWER_LEFT',
  LEFT = 'LEFT',
  UPPER_LEFT = 'UPPER_LEFT',
  BOTTOM = 'BOTTOM',
  CENTER = 'CENTER',
  TOP = 'TOP',
  LOWER_RIGHT = 'LOWER_RIGHT',
  RIGHT = 'RIGHT',
  UPPER_RIGHT = 'UPPER_RIGHT',
}
