export enum ERoomTypes {
  DEFAULT = 'DEFAULT',
  // Kitchen & Dinning
  KITCHEN = 'KITCHEN',
  DINING = 'DINING',
  PANTRY = 'PANTRY',
  BREAKFAST_AREA = 'BREAKFAST_AREA',
  BAR = 'BAR',
  // Bedroom & Closet
  MASTER_BEDROOM = 'MASTER_BEDROOM',
  BEDROOM = 'BEDROOM',
  WALK_IN_CLOSET = 'WALK_IN_CLOSET',
  DEN = 'DEN',
  CLOSET_REGULAR = 'CLOSET_REGULAR',
  // Bathroom
  MASTER_BATHROOM = 'MASTER_BATHROOM',
  ENSUITE = 'ENSUITE',
  POWDER = 'POWDER',
  // Living
  LIVING_ROOM = 'LIVING_ROOM',
  FAMILY_ROOM = 'FAMILY_ROOM',
  // Utility
  LAUNDRY = 'LAUNDRY',
  LIBRARY_OFFICE = 'LIBRARY_OFFICE',
  WINE_CELLER = 'WINE_CELLER',
  ENTERTAINMENT_ROOM = 'ENTERTAINMENT_ROOM',
  THEATRE_ROOM = 'THEATRE_ROOM',
  MUDROOM = 'MUDROOM',
  // Walkway
  STAIRCASE = 'STAIRCASE',
  ENTRY = 'ENTRY',
  // Aisle & Balcony
  FOYER = 'FOYER',
  BALCONY = 'BALCONY',
}
